### ISSUE TITLE
Sonar Scanner throws exception when importing test and coverage reports.

### ISSUE THREAD

**Issue by rvisharma** [jmecosta/sonar-fsharp-plugin#16]
Hi,
While running sonar-scanner  without importing coverage, the plugin works perfectly.
But when i try to import the test report and coverage report. An Exception gets thrown.
Please see the details below.

## Setup

- Sonarqube 6.2
- FSharpLint 0.4.12
- NUnit - 3.4.1
- Open Cover - 4.6.166

## Sonar config
```
# Project identification
sonar.projectKey=CoverageTest
sonar.projectVersion=1.0
sonar.projectName=CoverageTest

#Default source code encoding
sonar.sourceEncoding=UTF-8
sonar.visualstudio.enable=true

# Info required for Sonar 
sonar.sources=CoverageTest

sonar.dotnet.visualstudio.solution.file=CoverageTest.sln

sonar.fs.nunit.reportsPaths=CoverageTest_Test/bin/Debug/TestResult.xml
sonar.fs.opencover.reportsPaths=CoverageTest_Test/bin/Debug/results.xml

```

**Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/bas
e/Splitter**

```
INFO: Sensor F# (done) | time=8325ms
INFO: Sensor Coverage Report Import
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common
e/Splitter
        at org.sonar.plugins.dotnet.tests.CoverageAggregator.aggregate(Cover
ggregator.java:106)
        at org.sonar.plugins.dotnet.tests.CoverageAggregator.aggregate(Cover
ggregator.java:91)
        at org.sonar.plugins.dotnet.tests.CoverageReportImportSensor.analyze
erageReportImportSensor.java:68)
        at org.sonar.plugins.dotnet.tests.CoverageReportImportSensor.execute
erageReportImportSensor.java:63)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java

        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExe
r.java:57)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.
:49)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPh
xecutor.java:78)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleSca
tainer.java:182)
        at org.sonar.core.platform.ComponentContainer.startComponents(Compon
ontainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentConta
.java:127)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanConta
.java:247)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(Proje
anContainer.java:242)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectS
ontainer.java:232)
        at org.sonar.core.platform.ComponentContainer.startComponents(Compon
ontainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentConta
.java:127)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.j
86)
        at org.sonar.core.platform.ComponentContainer.startComponents(Compon
ontainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentConta
.java:127)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalCon
er.java:115)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.
ute(BatchIsolatedLauncher.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorI
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodA
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke
latedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedSca
.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedS
er.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Splitter
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstSt
gy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 34 more
Terminate batch job (Y/N)?
```

## Reports
- [Exception Snip](https://cloud.githubusercontent.com/assets/5556114/23652458/0aa6eff6-034f-11e7-8912-b73fa6c7ddd8.png)
- [NUnit Report](https://github.com/jmecsoftware/sonar-fsharp-plugin/files/824103/TestResult.txt)
- [OpenCover Report](https://github.com/jmecsoftware/sonar-fsharp-plugin/files/824102/results.txt)

**Comment by jmecosta** [comment]
interesting, that works for us. This from the org.sonar.plugins.dotnet.tests, can you show what plugins have you installed in your sonarqube?

**Comment by rvisharma** [comment]
**Mostly all plugins are from official sonarqube plugin centre.**

- sonar-csharp-plugin-5.8.0.660.jar
- sonar-css-plugin-3.1.jar
- sonar-java-plugin-4.3.0.7717.jar
- sonar-javascript-plugin-2.21.0.4409.jar
- sonar-scm-git-plugin-1.2.jar
- sonar-scm-svn-plugin-1.3.jar
- sonar-typescript-plugin-1.0.0.jar
- sonar-web-plugin-2.5.0.476.jar
- sonarqube-fsharp-plugin-1.0.0.jar


![2017-03-07 17_13_29-thehub-module-server - remote desktop connection](https://cloud.githubusercontent.com/assets/5556114/23655034/7028e708-0359-11e7-9f69-536cc27c9ee7.png)

_PS - also updated sonar config properties above, mentioned wrong path before for reports_

**Comment by rvisharma** [comment]
did some digging, code breaks at this line [L106](https://github.com/SonarSource/sonar-dotnet-tests-library/blob/master/src/main/java/org/sonar/plugins/dotnet/tests/CoverageAggregator.java#L106)

```
for (String reportPathPattern : Splitter.on(',').trimResults().omitEmptyStrings().split(reportPaths)) {
      for (File reportFile : wildcardPatternFileProvider.listFiles(reportPathPattern)) {
        aggregatedCoverage.mergeWith(coverageCache.readCoverageFromCacheOrParse(parser, reportFile));
      }
    }
```

It's throwing *java.lang.NoClassDefFoundError* for **Splitter** Class

**Comment by jmecosta** [comment]
Did you customize the plugin? I suspect it's because the c# plugin removed
dependency to Google. And suggest rollback to previous version of c# plugin
until I upgrade the lib

**Comment by rvisharma** [comment]
No, i didn't perform any customization to the plugin.

The issue got resolved by manually pasting **guava-10.0.1.jar** into the plugin's cache folder.

Explanation
When sonar unpacks all the plugins into cache folder, the lib folder for C# has guava in it.
but in fsharp plugin folder, guava was missing. Once i copy it to fsharp plugin, it works!

sonar-csharp-plugin-5.8.0.660.jar_unzip\META-INF\lib
![2017-03-07 19_17_58-thehub-module-server - remote desktop connection](https://cloud.githubusercontent.com/assets/5556114/23659066/ee780218-036a-11e7-81fa-0d4901b01129.png)

sonarqube-fsharp-plugin-1.0.0.jar_unzip\META-INF\lib
![2017-03-07 19_19_38-thehub-module-server - remote desktop connection](https://cloud.githubusercontent.com/assets/5556114/23659093/08e51c76-036b-11e7-8c9c-0788ca95c6e9.png)


As we see, guava was missing inside lib folder

**Comment by milbrandt** [comment]
@rvisharma Could you please test if there are still exceptions in release 1.0.5? You'll need Sonarqube 6.7 or newer to run the plugin. Regarding Tests and code coverage see the Readme markdown.

**Comment by milbrandt** [comment]
Closed as no update from original poster.
