### ISSUE TITLE
Error starting sonarqube after deploying plugin

### ISSUE THREAD

**Issue by richardjharding** [jmecosta/sonar-fsharp-plugin#18]
I copied the plugin v 1.0.1 into extensions as suggested but after restarting sonarqube I see this in the logs

```
2018.02.20 10:31:45 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register profile fs/Sonar way
2018.02.20 10:31:46 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: RuleDefinition not found for key fsharplint:RulesXmlDocumentationExceptionError
	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.lambda$insertActiveRule$4(BuiltInQProfileInsertImpl.java:145)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.insertActiveRule(BuiltInQProfileInsertImpl.java:145)
	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.lambda$create$0(BuiltInQProfileInsertImpl.java:86)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.create(BuiltInQProfileInsertImpl.java:87)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.register(RegisterQualityProfiles.java:112)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$1(RegisterQualityProfiles.java:83)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
	at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:320)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:88)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:47)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:88)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:85)
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:216)
	at org.sonar.server.platform.Platform.access$400(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:391)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:375)
	at java.lang.Thread.run(Thread.java:748)
2018.02.20 10:31:46 INFO  web[][o.s.p.StopWatcher] Stopping process
```

I'm currently running the sonarqube docker image v 6.5 - do I need to upgrade?

Or am I missing some other dependency?

Many thanks

Richard

**Comment by jmecosta** [comment]
no need, i forgot to push this commit some time ago. can you try with 1.0.2

**Comment by richardjharding** [comment]
Yep confirmed it all works fine with 1.02 - for anyone else thats with vsts docker build agents (linux) and sonarqube 6.5 - see also  #17 yes it does!
