### ISSUE TITLE
Could not load file or assembly 'Microsoft.Build.Utilities.v12.0

### ISSUE THREAD

**Issue by milbrandt** [jmecosta/sonar-fsharp-plugin#24]
Plugin release 1.0.3 on Sonarqube 7.3
On the build server only Visual Studio Enterprise 2017.9 is installed, no other verision of Visual Studio. This includes MSBuild 15.0

2019-01-07T14:32:40.7461240Z INFO: Source encoding: windows-1252, default locale: en_US
2019-01-07T14:32:40.7667208Z WARNING: WARN: Property 'sonar.fs.file.suffixes' is not declared as multi-values/property set but was read using 'getStringArray' method. The SonarQube plugin declaring this property should be updated.
2019-01-07T14:32:40.7706011Z INFO: Index files
2019-01-07T14:32:40.7727077Z INFO: 4 files indexed
2019-01-07T14:32:40.7728711Z INFO: Quality profile for fs: XXXX (F#)
2019-01-07T14:32:40.8094888Z INFO: Sensor SonarJavaXmlFileSensor [java]
2019-01-07T14:32:40.8095711Z INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=0ms
2019-01-07T14:32:40.8096150Z INFO: Sensor F# [sonarqubefsharpplugin]
2019-01-07T14:32:41.3400632Z INFO: [|"/i:D:\_1\13\.sonarqube\out\.sonar\mod5\fs-analysis-input.xml";
2019-01-07T14:32:41.3402280Z INFO:   "/o:D:\_1\13\.sonarqube\out\.sonar\mod5\fs-analysis-output.xml"|]
2019-01-07T14:32:41.7088818Z INFO:     **Failed: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Utilities.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.**
2019-01-07T14:32:41.7089113Z INFO: File name: 'Microsoft.Build.Utilities.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
2019-01-07T14:32:41.7089445Z INFO:    at Microsoft.FSharp.Compiler.MSBuildReferenceResolver.HighestInstalledNetFrameworkVersion()
2019-01-07T14:32:41.7089556Z INFO:    at Microsoft.FSharp.Compiler.MSBuildReferenceResolver.Resolver@364.Microsoft-FSharp-Compiler-ReferenceResolver-Resolver-HighestInstalledNetFrameworkVersion()
2019-01-07T14:32:41.7089712Z INFO:    at Microsoft.FSharp.Compiler.CompileOps.TcConfig..ctor(TcConfigBuilder data, Boolean validate)
2019-01-07T14:32:41.7089877Z INFO:    at Microsoft.FSharp.Compiler.CompileOps.TcConfig.Create(TcConfigBuilder builder, Boolean validate)
2019-01-07T14:32:41.7090012Z INFO:    at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.CreateScriptSourceTcConfig[a](Resolver referenceResolver, String filename, CodeContext codeContext, Boolean useSimpleResolution, Boolean useFsiAuxLib, FSharpOption`1 basicReferences, FSharpFunc`2 applyCommandLineArgs, Boolean assumeDotNetFramework)
2019-01-07T14:32:41.7090200Z INFO:    at Microsoft.FSharp.Compiler.CompileOps.ScriptPreprocessClosure.GetFullClosureOfScriptSource(CompilationThreadToken ctok, Resolver referenceResolver, String filename, String source, CodeContext codeContext, Boolean useSimpleResolution, Boolean useFsiAuxLib, LexResourceManager lexResourceManager, FSharpFunc`2 applyCommmandLineArgs, Boolean assumeDotNetFramework)
2019-01-07T14:32:41.7090506Z INFO:    at Microsoft.FSharp.Compiler.CompileOps.LoadClosure.ComputeClosureOfSourceText(CompilationThreadToken ctok, Resolver referenceResolver, String filename, String source, CodeContext implicitDefines, Boolean useSimpleResolution, Boolean useFsiAuxLib, LexResourceManager lexResourceManager, FSharpFunc`2 applyCompilerOptions, Boolean assumeDotNetFramework)
2019-01-07T14:32:41.7090662Z INFO:    at <StartupCode$FSharp-Compiler-Service>.$Service.GetProjectOptionsFromScript@2949-2.Invoke(ErrorScope _arg33)
2019-01-07T14:32:41.7090765Z INFO:    at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CancellableBuilder.Using[c,d](c resource, FSharpFunc`2 e)
2019-01-07T14:32:41.7091034Z INFO:    at <StartupCode$FSharp-Compiler-Service>.$Service.GetProjectOptionsFromScript@2947-1.Invoke(Unit unitVar)
2019-01-07T14:32:41.7091156Z INFO:    at Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CancellableModule.delay@766.Invoke(CancellationToken ct)
2019-01-07T14:32:41.7091305Z INFO:    at <StartupCode$FSharp-Compiler-Service>.$Reactor.EnqueueAndAwaitOpAsync@150-2.Invoke(CompilationThreadToken ctok)
2019-01-07T14:32:41.7091434Z INFO: --- End of stack trace from previous location where exception was thrown ---
2019-01-07T14:32:41.7091532Z INFO:    at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
2019-01-07T14:32:41.7091657Z INFO:    at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
2019-01-07T14:32:41.7091765Z INFO:    at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
2019-01-07T14:32:41.7091926Z INFO:    at FsSonarRunnerCore.SQAnalyser.GatherMetrics(String path, String input, SonarResoureMetrics resourceMetric)
2019-01-07T14:32:41.7092022Z INFO:    at FsSonarRunnerCore.SQAnalyser.GatherMetricsForResource(String path, String input)
2019-01-07T14:32:41.7092160Z INFO:    at FsSonarRunnerCore.SQAnalyser.RunAnalyses(String path, String input, String inputXmlConfig)
2019-01-07T14:32:41.7092262Z INFO:    at Program.main@49-1.Invoke(String c)
2019-01-07T14:32:41.7092388Z INFO:    at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
2019-01-07T14:32:41.7092480Z INFO:    at Program.main$cont@38(String[] argv, FSharpMap`2 arguments, Unit unitVar)
2019-01-07T14:32:41.7092592Z INFO: 
2019-01-07T14:32:41.7092669Z INFO: WRN: Assembly binding logging is turned OFF.
2019-01-07T14:32:41.7092796Z INFO: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
2019-01-07T14:32:41.7093432Z INFO: Note: There is some performance penalty associated with assembly bind failure logging.
2019-01-07T14:32:41.7093574Z INFO: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
2019-01-07T14:32:41.7183678Z ##[error]ERROR: Not able to parse file : {0}
2019-01-07T14:32:41.7191247Z **ERROR: Not able to parse file : {0}**
2019-01-07T14:32:41.7197308Z INFO: Sensor F# [sonarqubefsharpplugin] (done) | time=906ms

**Comment by milbrandt** [comment]
Is this the same as was reported in issue #12? As next VS will be released soon, any idea to resolve this with current VS2017 would be welcome.

**Comment by Autodidax86** [comment]
Any updates on this topic? We also require this fix.

**Comment by jmecosta** [comment]
i can try to upgrade the dependecies to use latest msbuild

**Comment by milbrandt** [comment]
@Autodidax86 
> Any updates on this topic? We also require this fix.

As we were waiting for several month now without any response, I proposed F# plugin at the official [Sonar community forum](https://community.sonarsource.com/t/any-plans-for-a-f-scanner/9289). Please support there the demand for F# as input to Sonar's choice of the next language to add.

**Comment by jmecosta** [comment]
@milbrandt thats absolutely fine of course, just as a side note. this is a open source project and contributions are more than welcome ;)

**Comment by milbrandt** [comment]
As far as I understood it is not possible to use any 3rd party plugin on Sonarcloud, is it? Therefore support by them is required to get F# support there. See [here](https://community.sonarsource.com/t/support-custom-plugin-on-sonar-cloud/4747).

@jmecosta As a side note, based on rare response on issues and PR I was not sure in which extend this project is still maintained.

**Comment by milbrandt** [comment]
seems to be fixed with PR #42 , exception no longer thrown

2019-06-08T09:04:44.3559342Z INFO: Sensor F# [sonarqubefsharpplugin]
2019-06-08T09:04:45.2689802Z INFO: [|"/i:D:\_1\2\.sonarqube\out\.sonar\mod9\fs-analysis-input.xml";
2019-06-08T09:04:45.2690322Z INFO:   "/o:D:\_1\2\.sonarqube\out\.sonar\mod9\fs-analysis-output.xml"|]
2019-06-08T09:04:48.0613159Z INFO: Lint NokFSharpLint.Application.Lint+LintFailure+FailedToParseFile
2019-06-08T09:04:48.3271430Z INFO: Lint NokFSharpLint.Application.Lint+LintFailure+FailedToParseFile
2019-06-08T09:04:48.4734890Z INFO: Lint NokFSharpLint.Application.Lint+LintFailure+FailedToParseFile
2019-06-08T09:04:48.6936113Z INFO: Lint NokFSharpLint.Application.Lint+LintFailure+FailedToParseFile
2019-06-08T09:04:49.0222643Z INFO: Lint NokFSharpLint.Application.Lint+LintFailure+FailedToParseFile
2019-06-08T09:04:49.3901549Z INFO: Lint NokFSharpLint.Application.Lint+LintFailure+FailedToParseFile
2019-06-08T09:04:49.6218402Z INFO: Lint NokFSharpLint.Application.Lint+LintFailure+FailedToParseFile
2019-06-08T09:04:49.6250392Z INFO: Write ouput xml to file D:\_1\2\.sonarqube\out\.sonar\mod9\fs-analysis-output.xml
2019-06-08T09:04:49.7221723Z INFO: Sensor F# [sonarqubefsharpplugin] (done) | time=5359ms
